language: android
sudo: false
android:
  components:
    - android-21
    - build-tools-21.1.1
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew build

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/db909d2de354884f570f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
